export const projects = [
  {
    id: 1,
    slug: "favorite-movie-database",
    title: "Favorite Movie Database",
    platform: "web",
    description:
      "A React/Next.js project with Tailwind CSS, reusable components, dark mode, and interactive design...",
    imageUrl: "/images/fire_and_ash.webp",
    techstack: ["React", "TypeScript", "Tailwind CSS", "Next.js"],
    features: [
      "Integration with MovieDB REST API with nested endpoints",
      "Reusable components using React client",
      "Search and Filter using the external API",
      "Responsive design",
      "Clean architecture",
      "Pagination and dynamic routing",
    ],
    repo_link: "https://github.com/shalawfatah/tmdb-api",
    live_link: "https://imdb-movies-api.netlify.app/",
    note: "",
  },
  {
    id: 2,
    slug: "ai-cv-cover-tweaker",
    title: "AI Resume & Cover Letter Optimizer",
    platform: "web",
    description:
      "Smart job application tool that analyzes job postings and tailors your resume and cover letter in real-time. Automatically emphasizes relevant skills, rewrites your professional summary, and generates personalized cover letters - all optimized for each specific role you're applying to.",
    imageUrl: "/images/cv_cover.png",
    techstack: [
      "React",
      "TypeScript",
      "Vite",
      "Redux Toolkit",
      "Tailwind CSS",
      "Gemini AI API",
    ],
    features: [
      "AI-powered job posting analysis with instant resume adaptation",
      "Automatic skill highlighting based on employer requirements",
      "Dynamic professional summary generation tailored to each role",
      "One-click AI-generated personalized cover letters",
      "Real-time side-by-side editing and preview",
      "PDF export for resume and cover letter",
      "Job application tracking to prevent duplicate submissions",
      "Redux state management for seamless data flow",
    ],
    repo_link: "https://github.com/shalawfatah/resume_cover_builder",
    live_link: "https://cvtweaker.netlify.app/",
    note: "",
  },
  {
    id: 3,
    slug: "invoice-generator",
    title: "Invoice Generator",
    platform: "mobile",
    description:
      "A cross-platform mobile app for creating invoices, estimates, and PTOs on the go, with automatic revenue and expense tracking.",
    imageUrl: "/images/invoice.webp",
    techstack: [
      "React",
      "React Native",
      "Supabase",
      "PostgreSQL",
      "Tailwind CSS",
    ],
    features: [
      "Create invoices to your clients with one click",
      "Create templates and customize them",
      "Tax calculations made easy on each invoice and PTO",
      "Calculate your revenue and spending automatically",
      "View charts and visul maps of your income",
      "Cross-platform mobile support (iOS & Android)",
      "Secure backend with Supabase and PostgreSQL",
    ],
    repo_link: "https://github.com/shalawfatah/invoice-generator.git",
    live_link: "https://apps.apple.com/us/app/invoice-generator/id6463258259",
    note: "",
  },
  {
    id: 4,
    slug: "design-library",
    title: "Production-ready Design Library",
    platform: "web & mobile",
    description:
      "A production-ready design library based on Tailwind with reusable components, consistent styling, and developer-friendly APIs for building scalable web applications.",
    imageUrl: "/images/design_library.avif",
    techstack: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Storybook"],
    features: [
      "Reusable UI components",
      "Responsive and mobile-first design",
      "Dark mode support",
      "Theming and customization",
      "Accessible and semantic HTML",
      "Documentation with live examples",
      "Optimized for production",
    ],
    repo_link: "https://github.com/shalawfatah/design-library",
    live_link: "https://designlib.netlify.app",
    note: "In progress now",
  },
  {
    id: 5,
    slug: "ai-dev-portfolio",
    title: "AI-Powered Developer Portfolio",
    platform: "web",
    description:
      "A modern developer portfolio built with Next.js that showcases my experience as a senior web developer, featuring an AI-integrated chatbot that can answer questions about my skills, projects, and background.",
    imageUrl: "/images/portfolio.png",
    techstack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "AI / LLM API",
    ],
    features: [
      "AI-powered chatbot trained to answer questions about my work and experience",
      "Modern, responsive portfolio design",
      "Project showcase with detailed case studies",
      "Server-side rendering and optimized performance",
      "Dark mode and accessible UI",
      "Scalable architecture using modern web tooling",
    ],
    repo_link: "https://github.com/shalawfatah/ai_integrated_profile",
    live_link: "https://shalawdev.netlify.app/",
    note: "",
  },
  {
    id: 6,
    slug: "teaching-platform",
    title: "Teaching Platform",
    platform: "mobile",
    description:
      "This is a React Native-based teaching platform where every teacher can open an account and publish videos for registered students.",
    imageUrl: "/images/teaching.png",
    techstack: [
      "React",
      "React Native",
      "Supabase",
      "PostgreSQL",
      "Tailwind CSS",
    ],
    features: [
      "Teacher and student account management",
      "Publish and stream video lessons",
      "Real-time chat with teachers and students",
      "Like, comment, and share posts",
      "Push notifications for messages and updates",
      "Cross-platform mobile support (iOS & Android)",
      "Secure backend with Supabase and PostgreSQL",
    ],
    repo_link: "https://github.com/shalawfatah/rava_crm",
    live_link: "https://apps.apple.com/us/app/rava/id6471388519",
    note: "",
  },
];
